import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

import { prisma } from "../db/client";

const Home: NextPage = (props: any) => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center w-1/2 min-h-screen mx-auto">
        <h1 className="font-extrabold text-center text-7xl">
          Create <span className="text-blue-500">T3</span> App
        </h1>

        <code> {props.questions}</code>
      </div>
    </>
  );
};

export default Home;

export const getServerSideProps = async () => {
  const questions = await prisma.pollQuestion.findMany();
  return { props: { questions: JSON.stringify(questions) } };
};
